package traffic;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class inputclass extends javax.swing.JFrame {

    /**
     * Creates new form inputclass
     */
    Connection conn;
        PreparedStatement pst;
        ResultSet rs;
        String msql;
        int count=0;
    public inputclass() {
        
        initComponents();
        
        conn=connectionclass.Makeconnection();
        if(conn==null)
        {
            JOptionPane.showMessageDialog(null, "Unable to make connection");
    mainwindow wref=new mainwindow();
    wref.setVisible(true);
    this.setVisible(false);
        }
        msql="select * from cardata";
        try
        {
            pst=conn.prepareStatement(msql);
            rs=pst.executeQuery();
        }
        catch(SQLException se)
{
    JOptionPane.showMessageDialog(null, se);
}
    catch(Exception er)
    {
    JOptionPane.showMessageDialog(null, er);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        carnumber = new javax.swing.JLabel();
        time = new javax.swing.JLabel();
        color = new javax.swing.JLabel();
        toc = new javax.swing.JTextField();
        carnumber2 = new javax.swing.JTextField();
        accident = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        clearall = new javax.swing.JButton();
        retreive = new javax.swing.JButton();
        home = new javax.swing.JButton();
        ownername = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        owner = new javax.swing.JTextField();
        mobile = new javax.swing.JTextField();
        address = new javax.swing.JTextField();
        dateofentry = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 204));
        jLabel1.setFont(new java.awt.Font("Algerian", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Data Entry Management");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 30, 390, 60));

        carnumber.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        carnumber.setText("Car Number");
        getContentPane().add(carnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 140, 30));

        time.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        time.setText("Time Of Crossing");
        getContentPane().add(time, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 140, 30));

        color.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        color.setText("Accident");
        getContentPane().add(color, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 90, 30));

        toc.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(toc, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 200, 30));

        carnumber2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(carnumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 200, 30));

        accident.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        accident.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        getContentPane().add(accident, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 200, 30));

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Date Of Data Entry");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 220, 170, 30));

        jPanel1.setBackground(new java.awt.Color(102, 255, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ACTION BUTTONS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Algerian", 1, 14), new java.awt.Color(51, 0, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 102, 255));

        add.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        add.setText("ADD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        clearall.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clearall.setText("CLEAR ALL");
        clearall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearallActionPerformed(evt);
            }
        });

        retreive.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        retreive.setText("Retrieve");
        retreive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retreiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(clearall)
                .addGap(72, 72, 72)
                .addComponent(retreive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addComponent(add)
                .addGap(44, 44, 44))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(retreive)
                    .addComponent(add)
                    .addComponent(clearall))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 540, 530, 100));

        home.setBackground(new java.awt.Color(255, 51, 153));
        home.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        home.setText("HOME");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });
        getContentPane().add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, -1));

        ownername.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        ownername.setText("Owner's Name ");
        getContentPane().add(ownername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Mobile Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        owner.setEditable(false);
        owner.setBackground(new java.awt.Color(255, 255, 255));
        owner.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(owner, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 200, 30));

        mobile.setEditable(false);
        mobile.setBackground(new java.awt.Color(255, 255, 255));
        mobile.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(mobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 200, 30));

        address.setEditable(false);
        address.setBackground(new java.awt.Color(255, 255, 255));
        address.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(address, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 450, 200, 30));

        dateofentry.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        getContentPane().add(dateofentry, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        // TODO add your handling code here:
        mainwindow wref=new mainwindow();
        wref.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_homeActionPerformed

    private void clearallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearallActionPerformed
        // TODO add your handling code here:
        carnumber2.setText("");
        toc.setText("");
        mobile.setText("");
        address.setText("");
        owner.setText("");
        carnumber2.enable(true);
        toc.enable(true);
    }//GEN-LAST:event_clearallActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        java.text.SimpleDateFormat date=new java.text.SimpleDateFormat("yyyy-MM-dd");
 String mobj=date.format(dateofentry.getDate());
 int fine;
 int time=(Integer.parseInt(toc.getText()));
 time=time%180;
 if(time>=0&&time<=60)
     fine=0;
 else
     fine=500;
 String acc=(String)accident.getSelectedItem();
 if(acc.equalsIgnoreCase("yes"))
     count++;
 try
 {
       msql="insert into cardata values(?,?,?,?,?,?,?) ";
       pst=conn.prepareStatement(msql);
       pst.setString(1,carnumber2.getText());
       pst.setString(2,mobj);
       pst.setString(3,owner.getText());
       pst.setString(4,mobile.getText());
       pst.setString(5,address.getText());
       pst.setInt(6,fine);
       pst.setInt(7,count);
       pst.executeUpdate();
       if(acc.equalsIgnoreCase("yes"))
           JOptionPane.showMessageDialog(null,"Accident has occured.Call the ambulance");
 }
 catch(SQLException se)
        {
            JOptionPane.showMessageDialog(null, se);
        }
        catch(Exception er)
        {
            JOptionPane.showMessageDialog(null, er);
        }
    }//GEN-LAST:event_addActionPerformed

    private void retreiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retreiveActionPerformed
        // TODO add your handling code here:
        String carno=carnumber2.getText();
        try
     {
         msql="select * from data where carno=?";
         pst=conn.prepareStatement(msql);
         pst.setString(1,carno);
         rs=pst.executeQuery();
         if(rs.next())
         {
             owner.setText(rs.getString(1));
             mobile.setText(rs.getString(3));
             address.setText(rs.getString(4));
         }   
     }
     catch(SQLException se)
        {
            JOptionPane.showMessageDialog(null, se);
        }
        catch(Exception er)
        {
            JOptionPane.showMessageDialog(null, er);
        }
    }//GEN-LAST:event_retreiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inputclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inputclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inputclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inputclass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inputclass().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accident;
    private javax.swing.JButton add;
    private javax.swing.JTextField address;
    private javax.swing.JLabel carnumber;
    private javax.swing.JTextField carnumber2;
    private javax.swing.JButton clearall;
    private javax.swing.JLabel color;
    private com.toedter.calendar.JDateChooser dateofentry;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField mobile;
    private javax.swing.JTextField owner;
    private javax.swing.JLabel ownername;
    private javax.swing.JButton retreive;
    private javax.swing.JLabel time;
    private javax.swing.JTextField toc;
    // End of variables declaration//GEN-END:variables
}
